/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfCriteriaTemplateDetailDto } from '../../models/api-response-of-criteria-template-detail-dto';

export interface ApiCriteriaTemplatesIdGet$Params {
  id: number;
}

export function apiCriteriaTemplatesIdGet(http: HttpClient, rootUrl: string, params: ApiCriteriaTemplatesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfCriteriaTemplateDetailDto>> {
  const rb = new RequestBuilder(rootUrl, apiCriteriaTemplatesIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfCriteriaTemplateDetailDto>;
    })
  );
}

apiCriteriaTemplatesIdGet.PATH = '/api/criteria-templates/{id}';
