/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfCriteriaTemplateSummaryDto } from '../../models/api-response-of-criteria-template-summary-dto';
import { CreateCriteriaTemplateDto } from '../../models/create-criteria-template-dto';

export interface ApiCriteriaTemplatesPost$Params {
      body: CreateCriteriaTemplateDto
}

export function apiCriteriaTemplatesPost(http: HttpClient, rootUrl: string, params: ApiCriteriaTemplatesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfCriteriaTemplateSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiCriteriaTemplatesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfCriteriaTemplateSummaryDto>;
    })
  );
}

apiCriteriaTemplatesPost.PATH = '/api/criteria-templates';
