/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfIReadOnlyListOfCriteriaTemplateSummaryDto } from '../../models/api-response-of-i-read-only-list-of-criteria-template-summary-dto';

export interface ApiCriteriaTemplatesGet$Params {
  subjectTypeId?: number;
}

export function apiCriteriaTemplatesGet(http: HttpClient, rootUrl: string, params?: ApiCriteriaTemplatesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfIReadOnlyListOfCriteriaTemplateSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiCriteriaTemplatesGet.PATH, 'get');
  if (params) {
    rb.query('subjectTypeId', params.subjectTypeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfIReadOnlyListOfCriteriaTemplateSummaryDto>;
    })
  );
}

apiCriteriaTemplatesGet.PATH = '/api/criteria-templates';
