/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfIReadOnlyListOfSubjectSummaryDto } from '../../models/api-response-of-i-read-only-list-of-subject-summary-dto';

export interface ApiSubjectsGet$Params {}

export function apiSubjectsGet(
  http: HttpClient,
  rootUrl: string,
  params?: ApiSubjectsGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfIReadOnlyListOfSubjectSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiSubjectsGet.PATH, 'get');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfIReadOnlyListOfSubjectSummaryDto>;
    }),
  );
}

apiSubjectsGet.PATH = '/api/subjects';
