/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfSubjectSummaryDto } from '../../models/api-response-of-subject-summary-dto';
import { CreateSubjectDto } from '../../models/create-subject-dto';

export interface ApiSubjectsPost$Params {
      body: CreateSubjectDto
}

export function apiSubjectsPost(http: HttpClient, rootUrl: string, params: ApiSubjectsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfSubjectSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiSubjectsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfSubjectSummaryDto>;
    })
  );
}

apiSubjectsPost.PATH = '/api/subjects';
