/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfSubjectDetailDto } from '../../models/api-response-of-subject-detail-dto';

export interface ApiSubjectsIdGet$Params {
  id: number;
}

export function apiSubjectsIdGet(
  http: HttpClient,
  rootUrl: string,
  params: ApiSubjectsIdGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfSubjectDetailDto>> {
  const rb = new RequestBuilder(rootUrl, apiSubjectsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfSubjectDetailDto>;
    }),
  );
}

apiSubjectsIdGet.PATH = '/api/subjects/{id}';
