/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/register': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['RegisterRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: {
					useCookies?: boolean;
					useSessionCookies?: boolean;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['LoginRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['AccessTokenResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/refresh': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['RefreshRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['AccessTokenResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/confirmEmail': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['MapIdentityApi-/confirmEmail'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/resendConfirmationEmail': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['ResendConfirmationEmailRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/forgotPassword': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['ForgotPasswordRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/resetPassword': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['ResetPasswordRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/manage/2fa': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['TwoFactorRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['TwoFactorResponse'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/manage/info': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['InfoResponse'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['InfoRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['InfoResponse'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/register': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Register a local account.
		 * @description POST /api/auth/register. Accepts a JSON body with userName, email, and password. Returns 200 with the created user identifiers or 400 with grouped Identity errors when validation fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['RegisterDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfRegisterResponseDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sign in with user name or email.
		 * @description POST /api/auth/login. Accepts userNameOrEmail and password. Returns 200 with a simple success flag on valid credentials, or 400/403/423 when Identity rejects the login for validation, policy, or lockout reasons.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['LoginDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfLoginResponseDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Locked */
				423: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/logout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sign out the current user.
		 * @description POST /api/auth/logout. Requires authentication. Clears the application cookie and returns 200 with a signedOut flag.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfLogoutResponseDto'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/password/reset/request': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Request a password reset email.
		 * @description POST /api/auth/password/reset/request. Accepts an email address and always returns 200 with dispatched=true. When the address matches a confirmed account a reset token is generated and emailed; unknown addresses receive the same response to avoid disclosure.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['PasswordResetTokenRequestDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfPasswordResetTokenDispatchResponseDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/password/reset/confirm': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Reset the password with a token.
		 * @description POST /api/auth/password/reset/confirm. Accepts email, token, and newPassword. Returns 200 with succeeded=true when the token is valid, or 400 with error codes when the reset fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['PasswordResetConfirmRequestDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfPasswordResetConfirmResponseDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get the current user's profile.
		 * @description GET /api/me. Requires authentication. Returns 200 with the caller's profile attributes including counts and security flags.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSelfProfileDto'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Update the current user's profile.
		 * @description PATCH /api/me. Requires authentication. Accepts optional displayName and avatarUrl fields. Returns 200 with the updated profile or 400 when validation fails.
		 */
		patch: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['SelfProfilePatchRequestDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSelfProfileDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		trace?: never;
	};
	'/api/me/followers': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List followers for the current user.
		 * @description GET /api/me/followers. Requires authentication. Supports page and pageSize query parameters and returns 200 with a paginated follower list including basic profile details. Responds with 400 for invalid pagination.
		 */
		get: {
			parameters: {
				query?: {
					Page?: number;
					PageSize?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSelfFollowPageDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/me/followers/{userId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Remove a follower from the current user.
		 * @description DELETE /api/me/followers/{userId}. Requires authentication. Removes the inbound follow relationship and returns 200 with removal status, or 400/401/404 when the request cannot be fulfilled.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					userId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSelfFollowerRemovalResultDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/me/following': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List users the current user follows.
		 * @description GET /api/me/following. Requires authentication. Supports page and pageSize query parameters and returns 200 with a paginated list of outbound follows. Responds with 400 for invalid pagination.
		 */
		get: {
			parameters: {
				query?: {
					Page?: number;
					PageSize?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSelfFollowPageDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/me/password/change': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Change the current user's password.
		 * @description POST /api/me/password/change. Requires authentication. Accepts currentPassword and newPassword in the body, returning 200 with the updated profile or 400 when validation fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['SelfPasswordChangeRequestDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSelfProfileDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/me/email/token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Request an email verification or change token.
		 * @description POST /api/me/email/token. Requires authentication. Accepts optional email and currentPassword values. Returns 200 with dispatch details, or 400/401/409 when validation fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['SelfEmailTokenRequestDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSelfEmailTokenDispatchResponseDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/me/email/confirm': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Confirm the user's email or email change.
		 * @description POST /api/me/email/confirm. Requires authentication. Accepts token and optional email. Returns 200 with the refreshed profile when confirmation succeeds, or 400/401/409 when validation fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['SelfEmailConfirmRequestDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSelfProfileDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/users': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Search users.
		 * @description GET /api/users. Requires authentication. Supports query, page, pageSize, and sort parameters to page through non-deleted users. Returns 200 with a paginated directory listing.
		 */
		get: {
			parameters: {
				query?: {
					query?: string;
					page?: number;
					pageSize?: number;
					sort?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfDirectoryPageDto'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Create a user (admin).
		 * @description POST /api/users. Requires admin authorization. Accepts userName, email, password, and optional fields such as roles. Returns 201 with detailed user information or 400 when Identity validation fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['CreateUserDto'];
				};
			};
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfUserDirectoryResponseDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/users/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get user directory details.
		 * @description GET /api/users/{id}. Requires authentication. Returns 200 with public profile data and, when the caller is an admin, extra sensitive information. Responds with 404 when the user cannot be found.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfUserDirectoryResponseDto'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		/**
		 * Soft delete a user (admin).
		 * @description DELETE /api/users/{id}. Requires admin authorization. Marks the account as deleted, locks it out indefinitely, and returns 200 with deletion status. Responds with 404 when the user cannot be found.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfUserDeleteResponseDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		/**
		 * Update a user (admin).
		 * @description PATCH /api/users/{id}. Requires admin authorization. Accepts optional profile fields, contact info, and role assignments. Returns 200 with updated admin detail or 400/404 when validation fails.
		 */
		patch: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['DirectoryAdminPatchRequestDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfUserDirectoryResponseDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		trace?: never;
	};
	'/api/users/{id}/lock': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Set a user's lockout (admin).
		 * @description POST /api/users/{id}/lock. Requires admin authorization. Accepts unlock=true to clear lockout or until to set a lockout date. Returns 200 with lockout status or 404 when the user is not found.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['LockUserRequestDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfUserLockResponseDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/follows/subjects/{subjectId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Follow a subject.
		 * @description POST /api/follows/subjects/{subjectId}. Requires authentication. Path parameter subjectId must reference an existing subject. Returns 201 with follow details, or 400/401/404/409 when validation fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					subjectId: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfFollowSubjectSummaryDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		/**
		 * Unfollow a subject.
		 * @description DELETE /api/follows/subjects/{subjectId}. Requires authentication. Removes the follow relationship and returns 200 with a removal flag, or 400/401/404 when the request cannot be completed.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					subjectId: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfFollowDeletionResultDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/follows/subjects': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List followed subjects.
		 * @description GET /api/follows/subjects. Requires authentication. Supports page and pageSize query parameters and returns a paginated collection ordered by follow time. Responds with 400 for invalid pagination or 401 when unauthenticated.
		 */
		get: {
			parameters: {
				query?: {
					Page?: number;
					PageSize?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfFollowSubjectPageDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/follows/subject-types/{subjectTypeId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Follow a subject type.
		 * @description POST /api/follows/subject-types/{subjectTypeId}. Requires authentication. Path parameter subjectTypeId must reference an existing type. Returns 201 with follow details, or 400/401/404/409 when validation fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					subjectTypeId: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfFollowSubjectTypeSummaryDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		/**
		 * Unfollow a subject type.
		 * @description DELETE /api/follows/subject-types/{subjectTypeId}. Requires authentication. Removes the follow relationship and returns 200 with a removal flag, or 400/401/404 when the request cannot be completed.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					subjectTypeId: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfFollowDeletionResultDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/follows/subject-types': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List followed subject types.
		 * @description GET /api/follows/subject-types. Requires authentication. Supports page and pageSize query parameters and returns a paginated collection with subject type metadata. Responds with 400 for invalid pagination or 401 when unauthenticated.
		 */
		get: {
			parameters: {
				query?: {
					Page?: number;
					PageSize?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfFollowSubjectTypePageDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/follows/users/{followedUserId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Follow a user.
		 * @description POST /api/follows/users/{followedUserId}. Requires authentication. Path parameter followedUserId must reference another existing user. Returns 201 with follow details, or 400/401/404/409 when validation fails (including self-follow attempts).
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					followedUserId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfFollowUserSummaryDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		/**
		 * Unfollow a user.
		 * @description DELETE /api/follows/users/{followedUserId}. Requires authentication. Removes the follow relationship and returns 200 with a removal flag, or 400/401/404 when the request cannot be completed.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					followedUserId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfFollowDeletionResultDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/follows/users': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List followed users.
		 * @description GET /api/follows/users. Requires authentication. Supports page and pageSize query parameters and returns a paginated collection enriched with followed user profile data. Responds with 400 for invalid pagination or 401 when unauthenticated.
		 */
		get: {
			parameters: {
				query?: {
					Page?: number;
					PageSize?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfFollowUserPageDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/feed': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get the authenticated user's feed.
		 * @description GET /api/feed. Requires authentication. Supports page, pageSize, after, and afterId query parameters for cursor-friendly pagination. Returns 200 with a feed page payload filtered to followed users, subjects, and subject types, or 400 when query values are invalid.
		 */
		get: {
			parameters: {
				query?: {
					Page?: number;
					PageSize?: number;
					After?: string;
					AfterId?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfFeedPageDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/ratings/subjects/{subjectId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get aggregate ratings for a subject.
		 * @description GET /api/ratings/subjects/{subjectId}. Returns 200 with the aggregate metrics when available, or 404 if the subject has no aggregate snapshot.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					subjectId: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSubjectAggregateDto'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Upsert aggregate ratings for a subject.
		 * @description POST /api/ratings/subjects/{subjectId}. Requires admin authorization. Accepts aggregate counts and metrics to create or update the snapshot. Returns 200 with the persisted aggregate, or 400/404 when validation fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					subjectId: number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['UpsertAggregateDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSubjectAggregateDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/subject-types': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List subject types.
		 * @description GET /api/subject-types. Returns 200 with all subject types ordered by id.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfIReadOnlyListOfSubjectTypeSummaryDto'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Create a subject type.
		 * @description POST /api/subject-types. Requires admin authorization. Accepts key, displayName, and optional settings. Returns 201 with the created subject type summary, or 400/409 when validation fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['CreateSubjectTypeDto'];
				};
			};
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSubjectTypeSummaryDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/subject-types/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/**
		 * Update a subject type.
		 * @description PUT /api/subject-types/{id}. Requires admin authorization. Accepts key, displayName, and optional settings. Returns 200 with the updated subject type summary, or 400/404/409 when validation fails.
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['UpdateSubjectTypeDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSubjectTypeSummaryDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		post?: never;
		/**
		 * Delete a subject type.
		 * @description DELETE /api/subject-types/{id}. Requires admin authorization. Removes the subject type when it is not referenced by subjects, returning 200 with deletion status or 404/409 on failure.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSubjectTypeDeleteResultDto'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/subjects': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List subjects.
		 * @description GET /api/subjects. Returns 200 with subject summaries (id, name, slug, subjectTypeId) for all non-deleted subjects sorted by id.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfIReadOnlyListOfSubjectSummaryDto'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Create a subject.
		 * @description POST /api/subjects. Requires admin authorization. Accepts name, slug, subjectTypeId, and optional attributes. Returns 201 with the created subject summary, or 400/409 when validation fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['CreateSubjectDto'];
				};
			};
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSubjectSummaryDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/subjects/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get subject details.
		 * @description GET /api/subjects/{id}. Returns 200 with detailed subject information including attributes and type metadata, or 404 if the subject does not exist or is deleted.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSubjectDetailDto'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		/**
		 * Update a subject.
		 * @description PUT /api/subjects/{id}. Requires admin authorization. Accepts name, slug, subjectTypeId, and optional attributes. Returns 200 with the updated subject summary, or 400/404/409 when validation fails.
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['UpdateSubjectDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSubjectSummaryDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		post?: never;
		/**
		 * Delete a subject.
		 * @description DELETE /api/subjects/{id}. Requires admin authorization. Soft deletes the subject and related reviews, removes aggregates, and returns 200 with deletion status. Responds with 404 when the subject cannot be found.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSubjectDeleteResultDto'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/criteria-templates': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List criteria templates.
		 * @description GET /api/criteria-templates. Optional query parameter subjectTypeId filters templates for a specific type. Returns 200 with template summaries ordered by id.
		 */
		get: {
			parameters: {
				query?: {
					subjectTypeId?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfIReadOnlyListOfCriteriaTemplateSummaryDto'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Create a criteria template.
		 * @description POST /api/criteria-templates. Requires admin authorization. Accepts subjectTypeId, key, displayName, and isRequired. Returns 201 with the created template summary, or 400/409 when validation fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['CreateCriteriaTemplateDto'];
				};
			};
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfCriteriaTemplateSummaryDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/criteria-templates/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get criteria template details.
		 * @description GET /api/criteria-templates/{id}. Returns 200 with template metadata and its subject type information, or 404 when the template is not found.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfCriteriaTemplateDetailDto'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/reviews/latest': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List the latest approved reviews.
		 * @description GET /api/reviews/latest. Supports page, pageSize, after, and afterId query parameters for cursor-friendly paging. Returns 200 with review summaries, or 400 when pagination values are invalid.
		 */
		get: {
			parameters: {
				query?: {
					Page?: number;
					PageSize?: number;
					After?: string;
					AfterId?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfLatestReviewsPageDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/reviews': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List reviews with optional filters.
		 * @description GET /api/reviews. Supports optional subjectId and userId query parameters. Returns 200 with review summaries for matching reviews, including pending entries.
		 */
		get: {
			parameters: {
				query?: {
					subjectId?: number;
					userId?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfIReadOnlyListOfReviewSummaryDto'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Create a review.
		 * @description POST /api/reviews. Requires authentication. Accepts subjectId, optional title/content, and optional ratings. Returns 201 with the created review summary, or 400/401/409 when validation fails.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['CreateReviewDto'];
				};
			};
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfReviewSummaryDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/reviews/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get review details.
		 * @description GET /api/reviews/{id}. Returns 200 with the full review, including subject data, author info, ratings, and media. Responds with 404 if the review does not exist or has been deleted.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfReviewDetailDto'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		/**
		 * Update a review.
		 * @description PUT /api/reviews/{id}. Requires authentication. Only the author may update the review. Accepts title, content, and ratings, returning 200 with the updated review summary or 400/401/403/404 when validation fails.
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['UpdateReviewDto'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfReviewSummaryDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		post?: never;
		/**
		 * Delete a review.
		 * @description DELETE /api/reviews/{id}. Requires authentication. Only the author may delete their review. Returns 200 with deletion status or 401/403/404 when the operation is not permitted.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfReviewDeleteResultDto'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/reviews/{id}/like': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Like a review.
		 * @description POST /api/reviews/{id}/like. Requires authentication. Adds a like for the specified review unless already liked. Returns 200 with the updated like state.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfReviewLikeResultDto'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		/**
		 * Unlike a review.
		 * @description DELETE /api/reviews/{id}/like. Requires authentication. Removes the current user's like if it exists. Returns 200 with the updated like state.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfReviewLikeResultDto'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/search': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Execute a search query.
		 * @description GET /api/search. Supports optional type, sort, limit, and cursor parameters.
		 */
		get: {
			parameters: {
				query: {
					query: string;
					type?: number;
					sort?: number;
					limit?: number;
					cursor?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfSearchResponseDto'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiResponseOfObject'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		AccessTokenResponse: {
			tokenType?: string | null;
			accessToken: string;
			/** Format: int64 */
			expiresIn: number;
			refreshToken: string;
		};
		AggregateMetricDto: {
			key: string;
			/** Format: double */
			value: number | null;
			/** Format: int32 */
			count: number | null;
			note: string | null;
		};
		ApiError: {
			code: string;
			message: string;
			/** @default null */
			details: {
				[key: string]: string[];
			} | null;
		} | null;
		ApiResponseOfCriteriaTemplateDetailDto: {
			success?: boolean;
			data?: components['schemas']['CriteriaTemplateDetailDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfCriteriaTemplateSummaryDto: {
			success?: boolean;
			data?: components['schemas']['CriteriaTemplateSummaryDto2'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfDirectoryPageDto: {
			success?: boolean;
			data?: components['schemas']['DirectoryPageDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfFeedPageDto: {
			success?: boolean;
			data?: components['schemas']['FeedPageDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfFollowDeletionResultDto: {
			success?: boolean;
			data?: components['schemas']['FollowDeletionResultDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfFollowSubjectPageDto: {
			success?: boolean;
			data?: components['schemas']['FollowSubjectPageDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfFollowSubjectSummaryDto: {
			success?: boolean;
			data?: components['schemas']['FollowSubjectSummaryDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfFollowSubjectTypePageDto: {
			success?: boolean;
			data?: components['schemas']['FollowSubjectTypePageDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfFollowSubjectTypeSummaryDto: {
			success?: boolean;
			data?: components['schemas']['FollowSubjectTypeSummaryDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfFollowUserPageDto: {
			success?: boolean;
			data?: components['schemas']['FollowUserPageDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfFollowUserSummaryDto: {
			success?: boolean;
			data?: components['schemas']['FollowUserSummaryDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfIReadOnlyListOfCriteriaTemplateSummaryDto: {
			success?: boolean;
			data?: components['schemas']['CriteriaTemplateSummaryDto'][] | null;
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfIReadOnlyListOfReviewSummaryDto: {
			success?: boolean;
			data?: components['schemas']['ReviewSummaryDto'][] | null;
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfIReadOnlyListOfSubjectSummaryDto: {
			success?: boolean;
			data?: components['schemas']['SubjectSummaryDto'][] | null;
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfIReadOnlyListOfSubjectTypeSummaryDto: {
			success?: boolean;
			data?: components['schemas']['SubjectTypeSummaryDto'][] | null;
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfLatestReviewsPageDto: {
			success?: boolean;
			data?: components['schemas']['LatestReviewsPageDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfLoginResponseDto: {
			success?: boolean;
			data?: components['schemas']['LoginResponseDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfLogoutResponseDto: {
			success?: boolean;
			data?: components['schemas']['LogoutResponseDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfObject: {
			success?: boolean;
			data?: unknown;
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfPasswordResetConfirmResponseDto: {
			success?: boolean;
			data?: components['schemas']['PasswordResetConfirmResponseDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfPasswordResetTokenDispatchResponseDto: {
			success?: boolean;
			data?: components['schemas']['PasswordResetTokenDispatchResponseDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfRegisterResponseDto: {
			success?: boolean;
			data?: components['schemas']['RegisterResponseDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfReviewDeleteResultDto: {
			success?: boolean;
			data?: components['schemas']['ReviewDeleteResultDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfReviewDetailDto: {
			success?: boolean;
			data?: components['schemas']['ReviewDetailDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfReviewLikeResultDto: {
			success?: boolean;
			data?: components['schemas']['ReviewLikeResultDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfReviewSummaryDto: {
			success?: boolean;
			data?: components['schemas']['ReviewSummaryDto2'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfSearchResponseDto: {
			success?: boolean;
			data?: components['schemas']['SearchResponseDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfSelfEmailTokenDispatchResponseDto: {
			success?: boolean;
			data?: components['schemas']['SelfEmailTokenDispatchResponseDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfSelfFollowerRemovalResultDto: {
			success?: boolean;
			data?: components['schemas']['SelfFollowerRemovalResultDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfSelfFollowPageDto: {
			success?: boolean;
			data?: components['schemas']['SelfFollowPageDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfSelfProfileDto: {
			success?: boolean;
			data?: components['schemas']['SelfProfileDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfSubjectAggregateDto: {
			success?: boolean;
			data?: components['schemas']['SubjectAggregateDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfSubjectDeleteResultDto: {
			success?: boolean;
			data?: components['schemas']['SubjectDeleteResultDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfSubjectDetailDto: {
			success?: boolean;
			data?: components['schemas']['SubjectDetailDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfSubjectSummaryDto: {
			success?: boolean;
			data?: components['schemas']['SubjectSummaryDto2'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfSubjectTypeDeleteResultDto: {
			success?: boolean;
			data?: components['schemas']['SubjectTypeDeleteResultDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfSubjectTypeSummaryDto: {
			success?: boolean;
			data?: components['schemas']['SubjectTypeSummaryDto2'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfUserDeleteResponseDto: {
			success?: boolean;
			data?: components['schemas']['UserDeleteResponseDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfUserDirectoryResponseDto: {
			success?: boolean;
			data?: components['schemas']['UserDirectoryResponseDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		ApiResponseOfUserLockResponseDto: {
			success?: boolean;
			data?: components['schemas']['UserLockResponseDto'];
			error?: components['schemas']['ApiError'];
			traceId?: string;
			/** Format: date-time */
			timestampUtc?: string;
		};
		CreateCriteriaTemplateDto: {
			/** Format: int32 */
			subjectTypeId: number;
			key: string;
			displayName: string;
			isRequired: boolean;
		};
		CreateReviewDto: {
			/** Format: int32 */
			subjectId: number;
			title: string | null;
			content: string | null;
			excerpt: string | null;
			ratings: components['schemas']['ReviewRatingDto'][] | null;
			tags: string[] | null;
		};
		CreateSubjectDto: {
			name: string;
			slug: string;
			/** Format: int32 */
			subjectTypeId: number;
			attributes: components['schemas']['SubjectAttributeDto'][] | null;
		};
		CreateSubjectTypeDto: {
			key: string;
			displayName: string;
			settings: components['schemas']['SubjectTypeSettingDto'][] | null;
		};
		CreateUserDto: {
			userName: string;
			email: string;
			password: string;
			displayName?: string | null;
			avatarUrl?: string | null;
			emailConfirmed?: boolean | null;
			roles?: string[] | null;
		};
		CriteriaTemplateDetailDto: {
			/** Format: int32 */
			id: number;
			/** Format: int32 */
			subjectTypeId: number;
			subjectTypeKey: string | null;
			subjectTypeDisplayName: string | null;
			key: string;
			displayName: string;
			isRequired: boolean;
		} | null;
		CriteriaTemplateSummaryDto: {
			/** Format: int32 */
			id: number;
			/** Format: int32 */
			subjectTypeId: number;
			key: string;
			displayName: string;
			isRequired: boolean;
		};
		CriteriaTemplateSummaryDto2: {
			/** Format: int32 */
			id: number;
			/** Format: int32 */
			subjectTypeId: number;
			key: string;
			displayName: string;
			isRequired: boolean;
		} | null;
		DirectoryAdminPatchRequestDto: {
			displayName?: components['schemas']['OptionalOfstring'];
			avatarUrl?: components['schemas']['OptionalOfstring'];
			phoneNumber?: components['schemas']['OptionalOfstring'];
			email?: components['schemas']['OptionalOfstring'];
			emailConfirmed?: components['schemas']['OptionalOfNullableOfboolean'];
			phoneNumberConfirmed?: components['schemas']['OptionalOfNullableOfboolean'];
			twoFactorEnabled?: components['schemas']['OptionalOfNullableOfboolean'];
			roles?: components['schemas']['OptionalOfIReadOnlyListOfstring'];
		};
		DirectoryPageDto: {
			/** Format: int32 */
			totalCount: number;
			/** Format: int32 */
			page: number;
			/** Format: int32 */
			pageSize: number;
			items: components['schemas']['DirectoryUserDto'][];
		} | null;
		DirectoryUserDetailDto: {
			id: string;
			userName: string | null;
			displayName: string | null;
			avatarUrl: string | null;
			/** Format: date-time */
			createdAtUtc: string;
		};
		DirectoryUserDto: {
			id: string;
			userName: string | null;
			displayName: string | null;
			avatarUrl: string | null;
			/** Format: date-time */
			createdAtUtc: string;
		};
		FeedCursorDto: {
			/** Format: date-time */
			createdAtUtc: string;
			/** Format: int64 */
			reviewId: number;
		} | null;
		FeedItemDto: {
			/** Format: int64 */
			reviewId: number;
			/** Format: date-time */
			createdAtUtc: string;
			/** Format: int32 */
			subjectId: number;
			subjectName: string | null;
			subjectSlug: string | null;
			/** Format: int32 */
			subjectTypeId: number | null;
			title: string | null;
			content: string | null;
			authorId: string | null;
			authorUserName: string | null;
			authorDisplayName: string | null;
			authorAvatarUrl: string | null;
		};
		FeedPageDto: {
			/** Format: int32 */
			totalCount: number;
			/** Format: int32 */
			page: number;
			/** Format: int32 */
			pageSize: number;
			items: components['schemas']['FeedItemDto'][];
			nextCursor: components['schemas']['FeedCursorDto'];
			hasMore: boolean;
		} | null;
		FollowDeletionResultDto: {
			/** Format: int64 */
			followId: number;
			removed: boolean;
		} | null;
		FollowSubjectPageDto: {
			/** Format: int32 */
			totalCount: number;
			/** Format: int32 */
			page: number;
			/** Format: int32 */
			pageSize: number;
			items: components['schemas']['FollowSubjectSummaryDto2'][];
		} | null;
		FollowSubjectSummaryDto: {
			/** Format: int64 */
			followId: number;
			/** Format: int32 */
			subjectId: number;
			subjectName: string;
			subjectSlug: string;
			/** Format: date-time */
			followedAtUtc: string;
		} | null;
		FollowSubjectSummaryDto2: {
			/** Format: int64 */
			followId: number;
			/** Format: int32 */
			subjectId: number;
			subjectName: string;
			subjectSlug: string;
			/** Format: date-time */
			followedAtUtc: string;
		};
		FollowSubjectTypePageDto: {
			/** Format: int32 */
			totalCount: number;
			/** Format: int32 */
			page: number;
			/** Format: int32 */
			pageSize: number;
			items: components['schemas']['FollowSubjectTypeSummaryDto2'][];
		} | null;
		FollowSubjectTypeSummaryDto: {
			/** Format: int64 */
			followId: number;
			/** Format: int32 */
			subjectTypeId: number;
			subjectTypeKey: string;
			subjectTypeDisplayName: string;
			/** Format: date-time */
			followedAtUtc: string;
		} | null;
		FollowSubjectTypeSummaryDto2: {
			/** Format: int64 */
			followId: number;
			/** Format: int32 */
			subjectTypeId: number;
			subjectTypeKey: string;
			subjectTypeDisplayName: string;
			/** Format: date-time */
			followedAtUtc: string;
		};
		FollowUserPageDto: {
			/** Format: int32 */
			totalCount: number;
			/** Format: int32 */
			page: number;
			/** Format: int32 */
			pageSize: number;
			items: components['schemas']['FollowUserSummaryDto2'][];
		} | null;
		FollowUserSummaryDto: {
			/** Format: int64 */
			followId: number;
			userId: string;
			userName: string | null;
			displayName: string | null;
			avatarUrl: string | null;
			/** Format: date-time */
			followedAtUtc: string;
		} | null;
		FollowUserSummaryDto2: {
			/** Format: int64 */
			followId: number;
			userId: string;
			userName: string | null;
			displayName: string | null;
			avatarUrl: string | null;
			/** Format: date-time */
			followedAtUtc: string;
		};
		ForgotPasswordRequest: {
			email: string;
		};
		HttpValidationProblemDetails: {
			type?: string | null;
			title?: string | null;
			/** Format: int32 */
			status?: number | null;
			detail?: string | null;
			instance?: string | null;
			errors?: {
				[key: string]: string[];
			};
		};
		InfoRequest: {
			newEmail?: string | null;
			newPassword?: string | null;
			oldPassword?: string | null;
		};
		InfoResponse: {
			email: string;
			isEmailConfirmed: boolean;
		};
		LatestReviewsCursorDto: {
			/** Format: date-time */
			createdAtUtc: string;
			/** Format: int64 */
			reviewId: number;
		} | null;
		LatestReviewsPageDto: {
			/** Format: int32 */
			totalCount: number;
			/** Format: int32 */
			page: number;
			/** Format: int32 */
			pageSize: number;
			items: components['schemas']['ReviewSummaryDto'][];
			nextCursor: components['schemas']['LatestReviewsCursorDto'];
			hasMore: boolean;
		} | null;
		LockUserRequestDto: {
			/** Format: date-time */
			until?: string | null;
			unlock?: boolean | null;
		};
		LoginDto: {
			userNameOrEmail: string;
			password: string;
		};
		LoginRequest: {
			email: string;
			password: string;
			twoFactorCode?: string | null;
			twoFactorRecoveryCode?: string | null;
		};
		LoginResponseDto: {
			signedIn: boolean;
		} | null;
		LogoutResponseDto: {
			signedOut: boolean;
		} | null;
		MediaType: number;
		OptionalOfIReadOnlyListOfstring: unknown;
		OptionalOfNullableOfboolean: unknown;
		OptionalOfstring: unknown;
		PasswordResetConfirmRequestDto: {
			email: string;
			token: string;
			newPassword: string;
		};
		PasswordResetConfirmResponseDto: {
			succeeded: boolean;
		} | null;
		PasswordResetTokenDispatchResponseDto: {
			dispatched: boolean;
		} | null;
		PasswordResetTokenRequestDto: {
			email: string;
		};
		RefreshRequest: {
			refreshToken: string;
		};
		RegisterDto: {
			userName: string;
			email: string;
			password: string;
		};
		RegisterRequest: {
			email: string;
			password: string;
		};
		RegisterResponseDto: {
			userId: string | null;
			userName: string | null;
			email: string | null;
		} | null;
		ResendConfirmationEmailRequest: {
			email: string;
		};
		ResetPasswordRequest: {
			email: string;
			resetCode: string;
			newPassword: string;
		};
		ReviewDeleteResultDto: {
			/** Format: int64 */
			id: number;
			deleted: boolean;
		} | null;
		ReviewDetailDto: {
			/** Format: int64 */
			id: number;
			/** Format: int32 */
			subjectId: number;
			subjectName: string | null;
			subjectSlug: string | null;
			userId: string;
			authorUserName: string | null;
			authorDisplayName: string | null;
			authorAvatarUrl: string | null;
			title: string | null;
			content: string | null;
			excerpt: string | null;
			excerptIsAuto: boolean;
			tags: string[];
			ratings: components['schemas']['ReviewRatingDto'][];
			/** Format: int32 */
			likeCount: number;
			isLikedByCurrentUser: boolean;
			status: components['schemas']['ReviewStatus'];
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
			media: components['schemas']['ReviewMediaDto'][];
		} | null;
		ReviewLikeResultDto: {
			/** Format: int64 */
			reviewId: number;
			/** Format: int32 */
			likeCount: number;
			isLikedByCurrentUser: boolean;
		} | null;
		ReviewMediaDto: {
			/** Format: int64 */
			id: number;
			url: string;
			type: components['schemas']['MediaType'];
			metadata: components['schemas']['ReviewMediaMetadataDto'][];
		};
		ReviewMediaMetadataDto: {
			key: string;
			value: string | null;
			note: string | null;
		};
		ReviewRatingDto: {
			key: string;
			/** Format: double */
			score: number;
			label: string | null;
		};
		ReviewStatus: number;
		ReviewSummaryDto: {
			/** Format: int64 */
			id: number;
			/** Format: int32 */
			subjectId: number;
			subjectName: string | null;
			userId: string;
			authorUserName: string | null;
			authorDisplayName: string | null;
			authorAvatarUrl: string | null;
			title: string | null;
			content: string | null;
			excerpt: string | null;
			excerptIsAuto: boolean;
			ratings: components['schemas']['ReviewRatingDto'][];
			status: components['schemas']['ReviewStatus'];
			/** Format: date-time */
			createdAt: string;
			tags: string[];
			/** Format: int32 */
			likeCount: number;
			isLikedByCurrentUser: boolean;
		};
		ReviewSummaryDto2: {
			/** Format: int64 */
			id: number;
			/** Format: int32 */
			subjectId: number;
			subjectName: string | null;
			userId: string;
			authorUserName: string | null;
			authorDisplayName: string | null;
			authorAvatarUrl: string | null;
			title: string | null;
			content: string | null;
			excerpt: string | null;
			excerptIsAuto: boolean;
			ratings: components['schemas']['ReviewRatingDto'][];
			status: components['schemas']['ReviewStatus'];
			/** Format: date-time */
			createdAt: string;
			tags: string[];
			/** Format: int32 */
			likeCount: number;
			isLikedByCurrentUser: boolean;
		} | null;
		SearchResponseDto: {
			results: components['schemas']['SearchResultDto'][];
			sort: string;
			type: string;
			nextCursor: string | null;
		} | null;
		SearchResultDto: {
			type: components['schemas']['SearchResultType'];
			/** Format: int32 */
			subjectId: number | null;
			/** Format: int64 */
			reviewId: number | null;
			title: string;
			subtitle: string | null;
			excerpt: string | null;
			/** Format: double */
			score: number;
			/** Format: date-time */
			createdAtUtc: string;
		};
		/** @enum {unknown} */
		SearchResultType: 'Subject' | 'Review';
		SelfEmailConfirmRequestDto: {
			email?: string | null;
			token: string;
		};
		SelfEmailTokenDispatchResponseDto: {
			userId: string;
			email: string;
			purpose: string;
		} | null;
		SelfEmailTokenRequestDto: {
			email?: string | null;
			currentPassword?: string | null;
		};
		SelfFollowerRemovalResultDto: {
			userId: string;
			removed: boolean;
		} | null;
		SelfFollowPageDto: {
			/** Format: int32 */
			totalCount: number;
			/** Format: int32 */
			page: number;
			/** Format: int32 */
			pageSize: number;
			items: components['schemas']['SelfFollowSummaryDto'][];
		} | null;
		SelfFollowSummaryDto: {
			userId: string;
			userName: string | null;
			displayName: string | null;
			avatarUrl: string | null;
			/** Format: date-time */
			followedAtUtc: string;
		};
		SelfPasswordChangeRequestDto: {
			currentPassword: string;
			newPassword: string;
		};
		SelfProfileDto: {
			id: string;
			userName: string | null;
			displayName: string | null;
			email: string | null;
			emailConfirmed: boolean;
			phoneNumber: string | null;
			phoneNumberConfirmed: boolean;
			avatarUrl: string | null;
			twoFactorEnabled: boolean;
			lockoutEnabled: boolean;
			/** Format: date-time */
			lockoutEnd: string | null;
			/** Format: date-time */
			createdAtUtc: string;
			/** Format: int32 */
			followersCount: number;
			/** Format: int32 */
			followingCount: number;
		} | null;
		SelfProfilePatchRequestDto: {
			displayName?: components['schemas']['OptionalOfstring'];
			avatarUrl?: components['schemas']['OptionalOfstring'];
		};
		SensitiveUserInfoDto: {
			email: string | null;
			emailConfirmed: boolean;
			phoneNumber: string | null;
			phoneNumberConfirmed: boolean;
			twoFactorEnabled: boolean;
			lockoutEnabled: boolean;
			/** Format: date-time */
			lockoutEnd: string | null;
			roles: string[];
		} | null;
		SubjectAggregateDto: {
			/** Format: int32 */
			subjectId: number;
			/** Format: int32 */
			countReviews: number;
			/** Format: double */
			avgOverall: number;
			metrics: components['schemas']['AggregateMetricDto'][];
			/** Format: date-time */
			updatedAt: string;
		} | null;
		SubjectAttributeDto: {
			key: string;
			value: string | null;
			note: string | null;
		};
		SubjectDeleteResultDto: {
			/** Format: int32 */
			id: number;
			deleted: boolean;
		} | null;
		SubjectDetailDto: {
			/** Format: int32 */
			id: number;
			name: string;
			slug: string;
			/** Format: int32 */
			subjectTypeId: number;
			subjectTypeKey: string | null;
			subjectTypeDisplayName: string | null;
			attributes: components['schemas']['SubjectAttributeDto'][];
			/** Format: date-time */
			createdAt: string;
		} | null;
		SubjectSummaryDto: {
			/** Format: int32 */
			id: number;
			name: string;
			slug: string;
			/** Format: int32 */
			subjectTypeId: number;
		};
		SubjectSummaryDto2: {
			/** Format: int32 */
			id: number;
			name: string;
			slug: string;
			/** Format: int32 */
			subjectTypeId: number;
		} | null;
		SubjectTypeDeleteResultDto: {
			/** Format: int32 */
			id: number;
			deleted: boolean;
		} | null;
		SubjectTypeSettingDto: {
			key: string;
			value: string | null;
			note: string | null;
		};
		SubjectTypeSummaryDto: {
			/** Format: int32 */
			id: number;
			key: string;
			displayName: string;
		};
		SubjectTypeSummaryDto2: {
			/** Format: int32 */
			id: number;
			key: string;
			displayName: string;
		} | null;
		TwoFactorRequest: {
			enable?: boolean | null;
			twoFactorCode?: string | null;
			resetSharedKey?: boolean;
			resetRecoveryCodes?: boolean;
			forgetMachine?: boolean;
		};
		TwoFactorResponse: {
			sharedKey: string;
			/** Format: int32 */
			recoveryCodesLeft: number;
			recoveryCodes?: string[] | null;
			isTwoFactorEnabled: boolean;
			isMachineRemembered: boolean;
		};
		UpdateReviewDto: {
			title: string;
			content: string | null;
			excerpt: string | null;
			ratings: components['schemas']['ReviewRatingDto'][] | null;
			tags: string[] | null;
		};
		UpdateSubjectDto: {
			name: string;
			slug: string;
			/** Format: int32 */
			subjectTypeId: number;
			attributes: components['schemas']['SubjectAttributeDto'][] | null;
		};
		UpdateSubjectTypeDto: {
			key: string;
			displayName: string;
			settings: components['schemas']['SubjectTypeSettingDto'][] | null;
		};
		UpsertAggregateDto: {
			/** Format: int32 */
			countReviews: number;
			/** Format: double */
			avgOverall: number;
			metrics: components['schemas']['AggregateMetricDto'][] | null;
		};
		UserDeleteResponseDto: {
			userId: string;
			isDeleted: boolean;
		} | null;
		UserDirectoryResponseDto: {
			public: components['schemas']['DirectoryUserDetailDto'];
			sensitive: components['schemas']['SensitiveUserInfoDto'];
		} | null;
		UserLockResponseDto: {
			userId: string;
			/** Format: date-time */
			lockoutEnd: string | null;
		} | null;
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	'MapIdentityApi-/confirmEmail': {
		parameters: {
			query: {
				userId: string;
				code: string;
				changedEmail?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
