/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfFollowSubjectTypeSummaryDto } from '../../models/api-response-of-follow-subject-type-summary-dto';

export interface ApiFollowsSubjectTypesSubjectTypeIdPost$Params {
  subjectTypeId: number;
}

export function apiFollowsSubjectTypesSubjectTypeIdPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiFollowsSubjectTypesSubjectTypeIdPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfFollowSubjectTypeSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiFollowsSubjectTypesSubjectTypeIdPost.PATH, 'post');
  if (params) {
    rb.path('subjectTypeId', params.subjectTypeId, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfFollowSubjectTypeSummaryDto>;
    }),
  );
}

apiFollowsSubjectTypesSubjectTypeIdPost.PATH = '/api/follows/subject-types/{subjectTypeId}';
