/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfFollowSubjectPageDto } from '../../models/api-response-of-follow-subject-page-dto';

export interface ApiFollowsSubjectsGet$Params {
  Page?: number;
  PageSize?: number;
}

export function apiFollowsSubjectsGet(http: HttpClient, rootUrl: string, params?: ApiFollowsSubjectsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfFollowSubjectPageDto>> {
  const rb = new RequestBuilder(rootUrl, apiFollowsSubjectsGet.PATH, 'get');
  if (params) {
    rb.query('Page', params.Page, {});
    rb.query('PageSize', params.PageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfFollowSubjectPageDto>;
    })
  );
}

apiFollowsSubjectsGet.PATH = '/api/follows/subjects';
