/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfFollowDeletionResultDto } from '../../models/api-response-of-follow-deletion-result-dto';

export interface ApiFollowsSubjectTypesSubjectTypeIdDelete$Params {
  subjectTypeId: number;
}

export function apiFollowsSubjectTypesSubjectTypeIdDelete(
  http: HttpClient,
  rootUrl: string,
  params: ApiFollowsSubjectTypesSubjectTypeIdDelete$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfFollowDeletionResultDto>> {
  const rb = new RequestBuilder(rootUrl, apiFollowsSubjectTypesSubjectTypeIdDelete.PATH, 'delete');
  if (params) {
    rb.path('subjectTypeId', params.subjectTypeId, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfFollowDeletionResultDto>;
    }),
  );
}

apiFollowsSubjectTypesSubjectTypeIdDelete.PATH = '/api/follows/subject-types/{subjectTypeId}';
