/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfFollowUserSummaryDto } from '../../models/api-response-of-follow-user-summary-dto';

export interface ApiFollowsUsersFollowedUserIdPost$Params {
  followedUserId: string;
}

export function apiFollowsUsersFollowedUserIdPost(http: HttpClient, rootUrl: string, params: ApiFollowsUsersFollowedUserIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfFollowUserSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiFollowsUsersFollowedUserIdPost.PATH, 'post');
  if (params) {
    rb.path('followedUserId', params.followedUserId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfFollowUserSummaryDto>;
    })
  );
}

apiFollowsUsersFollowedUserIdPost.PATH = '/api/follows/users/{followedUserId}';
