/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfFollowSubjectSummaryDto } from '../../models/api-response-of-follow-subject-summary-dto';

export interface ApiFollowsSubjectsSubjectIdPost$Params {
  subjectId: number;
}

export function apiFollowsSubjectsSubjectIdPost(http: HttpClient, rootUrl: string, params: ApiFollowsSubjectsSubjectIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfFollowSubjectSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiFollowsSubjectsSubjectIdPost.PATH, 'post');
  if (params) {
    rb.path('subjectId', params.subjectId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfFollowSubjectSummaryDto>;
    })
  );
}

apiFollowsSubjectsSubjectIdPost.PATH = '/api/follows/subjects/{subjectId}';
