/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface MapIdentityApiConfirmEmail$Params {
  userId: string;
  code: string;
  changedEmail?: string;
}

export function mapIdentityApiConfirmEmail(http: HttpClient, rootUrl: string, params: MapIdentityApiConfirmEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, mapIdentityApiConfirmEmail.PATH, 'get');
  if (params) {
    rb.query('userId', params.userId, {});
    rb.query('code', params.code, {});
    rb.query('changedEmail', params.changedEmail, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

mapIdentityApiConfirmEmail.PATH = '/confirmEmail';
