/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfPasswordResetTokenDispatchResponseDto } from '../../models/api-response-of-password-reset-token-dispatch-response-dto';
import { PasswordResetTokenRequestDto } from '../../models/password-reset-token-request-dto';

export interface ApiAuthPasswordResetRequestPost$Params {
      body: PasswordResetTokenRequestDto
}

export function apiAuthPasswordResetRequestPost(http: HttpClient, rootUrl: string, params: ApiAuthPasswordResetRequestPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfPasswordResetTokenDispatchResponseDto>> {
  const rb = new RequestBuilder(rootUrl, apiAuthPasswordResetRequestPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfPasswordResetTokenDispatchResponseDto>;
    })
  );
}

apiAuthPasswordResetRequestPost.PATH = '/api/auth/password/reset/request';
