/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfLoginResponseDto } from '../../models/api-response-of-login-response-dto';
import { LoginDto } from '../../models/login-dto';

export interface ApiAuthLoginPost$Params {
  body: LoginDto;
}

export function apiAuthLoginPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiAuthLoginPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfLoginResponseDto>> {
  const rb = new RequestBuilder(rootUrl, apiAuthLoginPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfLoginResponseDto>;
    }),
  );
}

apiAuthLoginPost.PATH = '/api/auth/login';
