/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfDirectoryPageDto } from '../../models/api-response-of-directory-page-dto';

export interface ApiUsersGet$Params {
  query?: string;
  page?: number;
  pageSize?: number;
  sort?: string;
}

export function apiUsersGet(http: HttpClient, rootUrl: string, params?: ApiUsersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfDirectoryPageDto>> {
  const rb = new RequestBuilder(rootUrl, apiUsersGet.PATH, 'get');
  if (params) {
    rb.query('query', params.query, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('sort', params.sort, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfDirectoryPageDto>;
    })
  );
}

apiUsersGet.PATH = '/api/users';
