/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfUserDirectoryResponseDto } from '../../models/api-response-of-user-directory-response-dto';
import { DirectoryAdminPatchRequestDto } from '../../models/directory-admin-patch-request-dto';

export interface ApiUsersIdPatch$Params {
  id: string;
      body: DirectoryAdminPatchRequestDto
}

export function apiUsersIdPatch(http: HttpClient, rootUrl: string, params: ApiUsersIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfUserDirectoryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, apiUsersIdPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfUserDirectoryResponseDto>;
    })
  );
}

apiUsersIdPatch.PATH = '/api/users/{id}';
