/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfUserDirectoryResponseDto } from '../../models/api-response-of-user-directory-response-dto';
import { CreateUserDto } from '../../models/create-user-dto';

export interface ApiUsersPost$Params {
  body: CreateUserDto;
}

export function apiUsersPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiUsersPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfUserDirectoryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, apiUsersPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfUserDirectoryResponseDto>;
    }),
  );
}

apiUsersPost.PATH = '/api/users';
