/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfUserDeleteResponseDto } from '../../models/api-response-of-user-delete-response-dto';

export interface ApiUsersIdDelete$Params {
  id: string;
}

export function apiUsersIdDelete(
  http: HttpClient,
  rootUrl: string,
  params: ApiUsersIdDelete$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfUserDeleteResponseDto>> {
  const rb = new RequestBuilder(rootUrl, apiUsersIdDelete.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfUserDeleteResponseDto>;
    }),
  );
}

apiUsersIdDelete.PATH = '/api/users/{id}';
