/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfSubjectTypeDeleteResultDto } from '../../models/api-response-of-subject-type-delete-result-dto';

export interface ApiSubjectTypesIdDelete$Params {
  id: number;
}

export function apiSubjectTypesIdDelete(
  http: HttpClient,
  rootUrl: string,
  params: ApiSubjectTypesIdDelete$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfSubjectTypeDeleteResultDto>> {
  const rb = new RequestBuilder(rootUrl, apiSubjectTypesIdDelete.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfSubjectTypeDeleteResultDto>;
    }),
  );
}

apiSubjectTypesIdDelete.PATH = '/api/subject-types/{id}';
