/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfIReadOnlyListOfSubjectTypeSummaryDto } from '../../models/api-response-of-i-read-only-list-of-subject-type-summary-dto';

export interface ApiSubjectTypesGet$Params {
}

export function apiSubjectTypesGet(http: HttpClient, rootUrl: string, params?: ApiSubjectTypesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfIReadOnlyListOfSubjectTypeSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiSubjectTypesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfIReadOnlyListOfSubjectTypeSummaryDto>;
    })
  );
}

apiSubjectTypesGet.PATH = '/api/subject-types';
