/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfSubjectTypeSummaryDto } from '../../models/api-response-of-subject-type-summary-dto';
import { CreateSubjectTypeDto } from '../../models/create-subject-type-dto';

export interface ApiSubjectTypesPost$Params {
      body: CreateSubjectTypeDto
}

export function apiSubjectTypesPost(http: HttpClient, rootUrl: string, params: ApiSubjectTypesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfSubjectTypeSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiSubjectTypesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfSubjectTypeSummaryDto>;
    })
  );
}

apiSubjectTypesPost.PATH = '/api/subject-types';
