/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfSubjectAggregateDto } from '../../models/api-response-of-subject-aggregate-dto';
import { UpsertAggregateDto } from '../../models/upsert-aggregate-dto';

export interface ApiRatingsSubjectsSubjectIdPost$Params {
  subjectId: number;
      body: UpsertAggregateDto
}

export function apiRatingsSubjectsSubjectIdPost(http: HttpClient, rootUrl: string, params: ApiRatingsSubjectsSubjectIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfSubjectAggregateDto>> {
  const rb = new RequestBuilder(rootUrl, apiRatingsSubjectsSubjectIdPost.PATH, 'post');
  if (params) {
    rb.path('subjectId', params.subjectId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfSubjectAggregateDto>;
    })
  );
}

apiRatingsSubjectsSubjectIdPost.PATH = '/api/ratings/subjects/{subjectId}';
