/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AggregateMetricDto {
  count: number | null;
  key: string;
  note: string | null;
  value: number | null;
}
