/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { FollowSubjectPageDto } from '../models/follow-subject-page-dto';
export interface ApiResponseOfFollowSubjectPageDto {
  data?: FollowSubjectPageDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
