/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { UserDirectoryResponseDto } from '../models/user-directory-response-dto';
export interface ApiResponseOfUserDirectoryResponseDto {
  data?: UserDirectoryResponseDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
