/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { SubjectSummaryDto } from '../models/subject-summary-dto';
export interface ApiResponseOfIReadOnlyListOfSubjectSummaryDto {
  data?: Array<SubjectSummaryDto> | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
