/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { ReviewDetailDto } from '../models/review-detail-dto';
export interface ApiResponseOfReviewDetailDto {
  data?: ReviewDetailDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
