/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { SelfFollowPageDto } from '../models/self-follow-page-dto';
export interface ApiResponseOfSelfFollowPageDto {
  data?: SelfFollowPageDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
