/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { CriteriaTemplateSummaryDto } from '../models/criteria-template-summary-dto';
export interface ApiResponseOfIReadOnlyListOfCriteriaTemplateSummaryDto {
  data?: Array<CriteriaTemplateSummaryDto> | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
