/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { RegisterResponseDto } from '../models/register-response-dto';
export interface ApiResponseOfRegisterResponseDto {
  data?: RegisterResponseDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
