/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { FollowUserSummaryDto } from '../models/follow-user-summary-dto';
export interface ApiResponseOfFollowUserSummaryDto {
  data?: FollowUserSummaryDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
