/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { PasswordResetTokenDispatchResponseDto } from '../models/password-reset-token-dispatch-response-dto';
export interface ApiResponseOfPasswordResetTokenDispatchResponseDto {
  data?: PasswordResetTokenDispatchResponseDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
