/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { SubjectDetailDto } from '../models/subject-detail-dto';
export interface ApiResponseOfSubjectDetailDto {
  data?: SubjectDetailDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
