/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { FollowSubjectTypeSummaryDto } from '../models/follow-subject-type-summary-dto';
export interface ApiResponseOfFollowSubjectTypeSummaryDto {
  data?: FollowSubjectTypeSummaryDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
