/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { SubjectAggregateDto } from '../models/subject-aggregate-dto';
export interface ApiResponseOfSubjectAggregateDto {
  data?: SubjectAggregateDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
