/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { CriteriaTemplateSummaryDto2 } from '../models/criteria-template-summary-dto-2';
export interface ApiResponseOfCriteriaTemplateSummaryDto {
  data?: CriteriaTemplateSummaryDto2 | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
