/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { SelfEmailTokenDispatchResponseDto } from '../models/self-email-token-dispatch-response-dto';
export interface ApiResponseOfSelfEmailTokenDispatchResponseDto {
  data?: SelfEmailTokenDispatchResponseDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
