/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { SubjectSummaryDto2 } from '../models/subject-summary-dto-2';
export interface ApiResponseOfSubjectSummaryDto {
  data?: SubjectSummaryDto2 | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
