/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { SearchResponseDto } from '../models/search-response-dto';
export interface ApiResponseOfSearchResponseDto {
  data?: SearchResponseDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
