/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { SubjectTypeSummaryDto2 } from '../models/subject-type-summary-dto-2';
export interface ApiResponseOfSubjectTypeSummaryDto {
  data?: SubjectTypeSummaryDto2 | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
