/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { LoginResponseDto } from '../models/login-response-dto';
export interface ApiResponseOfLoginResponseDto {
  data?: LoginResponseDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
