/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { PasswordResetConfirmResponseDto } from '../models/password-reset-confirm-response-dto';
export interface ApiResponseOfPasswordResetConfirmResponseDto {
  data?: PasswordResetConfirmResponseDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
