/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { UserDeleteResponseDto } from '../models/user-delete-response-dto';
export interface ApiResponseOfUserDeleteResponseDto {
  data?: UserDeleteResponseDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
