/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { LogoutResponseDto } from '../models/logout-response-dto';
export interface ApiResponseOfLogoutResponseDto {
  data?: LogoutResponseDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
