/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
export interface ApiErrorResponse {
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
