/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { FollowUserPageDto } from '../models/follow-user-page-dto';
export interface ApiResponseOfFollowUserPageDto {
  data?: FollowUserPageDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
