/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { ReviewSummaryDto2 } from '../models/review-summary-dto-2';
export interface ApiResponseOfReviewSummaryDto {
  data?: ReviewSummaryDto2 | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
