/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { FeedPageDto } from '../models/feed-page-dto';
export interface ApiResponseOfFeedPageDto {
  data?: FeedPageDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
