/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { UserLockResponseDto } from '../models/user-lock-response-dto';
export interface ApiResponseOfUserLockResponseDto {
  data?: UserLockResponseDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
