/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { LatestReviewsPageDto } from '../models/latest-reviews-page-dto';
export interface ApiResponseOfLatestReviewsPageDto {
  data?: LatestReviewsPageDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
