/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { FollowSubjectSummaryDto } from '../models/follow-subject-summary-dto';
export interface ApiResponseOfFollowSubjectSummaryDto {
  data?: FollowSubjectSummaryDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
