/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { SelfProfileDto } from '../models/self-profile-dto';
export interface ApiResponseOfSelfProfileDto {
  data?: SelfProfileDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
