/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { CriteriaTemplateDetailDto } from '../models/criteria-template-detail-dto';
export interface ApiResponseOfCriteriaTemplateDetailDto {
  data?: CriteriaTemplateDetailDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
