/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { DirectoryPageDto } from '../models/directory-page-dto';
export interface ApiResponseOfDirectoryPageDto {
  data?: DirectoryPageDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
