/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { SubjectTypeSummaryDto } from '../models/subject-type-summary-dto';
export interface ApiResponseOfIReadOnlyListOfSubjectTypeSummaryDto {
  data?: Array<SubjectTypeSummaryDto> | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
