/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { ReviewSummaryDto } from '../models/review-summary-dto';
export interface ApiResponseOfIReadOnlyListOfReviewSummaryDto {
  data?: Array<ReviewSummaryDto> | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
