/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiError } from '../models/api-error';
import { FollowSubjectTypePageDto } from '../models/follow-subject-type-page-dto';
export interface ApiResponseOfFollowSubjectTypePageDto {
  data?: FollowSubjectTypePageDto | null;
  error?: ApiError | null;
  success?: boolean;
  timestampUtc?: string;
  traceId?: string;
}
