/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubjectAttributeDto } from '../models/subject-attribute-dto';
export interface CreateSubjectDto {
  attributes: Array<SubjectAttributeDto> | null;
  name: string;
  slug: string;
  subjectTypeId: number;
}
