/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubjectTypeSettingDto } from '../models/subject-type-setting-dto';
export interface CreateSubjectTypeDto {
  displayName: string;
  key: string;
  settings: Array<SubjectTypeSettingDto> | null;
}
