/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCriteriaTemplateDto {
  displayName: string;
  isRequired: boolean;
  key: string;
  subjectTypeId: number;
}
