/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserDto {
  avatarUrl?: string | null;
  displayName?: string | null;
  email: string;
  emailConfirmed?: boolean | null;
  password: string;
  roles?: Array<string> | null;
  userName: string;
}
