/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type CriteriaTemplateSummaryDto2 = {
  id: number;
  subjectTypeId: number;
  key: string;
  displayName: string;
  isRequired: boolean;
} | null;
