/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CriteriaTemplateSummaryDto {
  displayName: string;
  id: number;
  isRequired: boolean;
  key: string;
  subjectTypeId: number;
}
