/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type CriteriaTemplateDetailDto = {
'id': number;
'subjectTypeId': number;
'subjectTypeKey': string | null;
'subjectTypeDisplayName': string | null;
'key': string;
'displayName': string;
'isRequired': boolean;
};

