/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OptionalOfIReadOnlyListOfstring } from '../models/optional-of-i-read-only-list-ofstring';
import { OptionalOfNullableOfboolean } from '../models/optional-of-nullable-ofboolean';
import { OptionalOfstring } from '../models/optional-ofstring';
export interface DirectoryAdminPatchRequestDto {
  avatarUrl?: OptionalOfstring;
  displayName?: OptionalOfstring;
  email?: OptionalOfstring;
  emailConfirmed?: OptionalOfNullableOfboolean;
  phoneNumber?: OptionalOfstring;
  phoneNumberConfirmed?: OptionalOfNullableOfboolean;
  roles?: OptionalOfIReadOnlyListOfstring;
  twoFactorEnabled?: OptionalOfNullableOfboolean;
}
