/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DirectoryUserDto {
  avatarUrl: string | null;
  createdAtUtc: string;
  displayName: string | null;
  id: string;
  userName: string | null;
}
