/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DirectoryUserDto } from '../models/directory-user-dto';
export type DirectoryPageDto = {
  totalCount: number;
  page: number;
  pageSize: number;
  items: Array<DirectoryUserDto>;
} | null;
