/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeedCursorDto } from '../models/feed-cursor-dto';
import { FeedItemDto } from '../models/feed-item-dto';
export type FeedPageDto = {
  totalCount: number;
  page: number;
  pageSize: number;
  items: Array<FeedItemDto>;
  nextCursor: FeedCursorDto | null;
  hasMore: boolean;
};
