/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type FollowSubjectTypeSummaryDto = ({
'followId': number;
'subjectTypeId': number;
'subjectTypeKey': string;
'subjectTypeDisplayName': string;
'followedAtUtc': string;
}) | null;

