/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FollowSubjectSummaryDto2 } from '../models/follow-subject-summary-dto-2';
export type FollowSubjectPageDto = {
  totalCount: number;
  page: number;
  pageSize: number;
  items: Array<FollowSubjectSummaryDto2>;
} | null;
