/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FollowUserSummaryDto2 } from '../models/follow-user-summary-dto-2';
export type FollowUserPageDto = ({
'totalCount': number;
'page': number;
'pageSize': number;
'items': Array<FollowUserSummaryDto2>;
}) | null;

