/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FollowUserSummaryDto2 {
  avatarUrl: string | null;
  displayName: string | null;
  followId: number;
  followedAtUtc: string;
  userId: string;
  userName: string | null;
}
