/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FollowSubjectSummaryDto2 {
  followId: number;
  followedAtUtc: string;
  subjectId: number;
  subjectName: string;
  subjectSlug: string;
}
