/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type FollowSubjectSummaryDto = {
  followId: number;
  subjectId: number;
  subjectName: string;
  subjectSlug: string;
  followedAtUtc: string;
} | null;
