/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type FollowUserSummaryDto = {
'followId': number;
'userId': string;
'userName': string | null;
'displayName': string | null;
'avatarUrl': string | null;
'followedAtUtc': string;
};

