/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FollowSubjectTypeSummaryDto2 } from '../models/follow-subject-type-summary-dto-2';
export type FollowSubjectTypePageDto = {
  totalCount: number;
  page: number;
  pageSize: number;
  items: Array<FollowSubjectTypeSummaryDto2>;
} | null;
