/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FollowSubjectTypeSummaryDto2 {
  followId: number;
  followedAtUtc: string;
  subjectTypeDisplayName: string;
  subjectTypeId: number;
  subjectTypeKey: string;
}
