/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HttpValidationProblemDetails {
  detail?: string | null;
  errors?: {
[key: string]: Array<string>;
};
  instance?: string | null;
  status?: number | null;
  title?: string | null;
  type?: string | null;
}
