/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginRequest {
  email: string;
  password: string;
  twoFactorCode?: string | null;
  twoFactorRecoveryCode?: string | null;
}
