/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MediaType } from '../models/media-type';
import { ReviewMediaMetadataDto } from '../models/review-media-metadata-dto';
export interface ReviewMediaDto {
  id: number;
  metadata: Array<ReviewMediaMetadataDto>;
  type: MediaType;
  url: string;
}
