/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewMediaDto } from '../models/review-media-dto';
import { ReviewRatingDto } from '../models/review-rating-dto';
import { ReviewStatus } from '../models/review-status';
export type ReviewDetailDto = {
'id': number;
'subjectId': number;
'subjectName': string | null;
'subjectSlug': string | null;
'userId': string;
'authorUserName': string | null;
'authorDisplayName': string | null;
'authorAvatarUrl': string | null;
'title': string | null;
'content': string | null;
'excerpt': string | null;
'excerptIsAuto': boolean;
'tags': Array<string>;
'ratings': Array<ReviewRatingDto>;
'likeCount': number;
'isLikedByCurrentUser': boolean;
'status': ReviewStatus;
'createdAt': string;
'updatedAt': string;
'media': Array<ReviewMediaDto>;
};

