/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewRatingDto } from '../models/review-rating-dto';
import { ReviewStatus } from '../models/review-status';
export type ReviewSummaryDto2 = {
  id: number;
  subjectId: number;
  subjectName: string | null;
  userId: string;
  authorUserName: string | null;
  authorDisplayName: string | null;
  authorAvatarUrl: string | null;
  title: string | null;
  content: string | null;
  excerpt: string | null;
  excerptIsAuto: boolean;
  ratings: Array<ReviewRatingDto>;
  status: ReviewStatus;
  createdAt: string;
  tags: Array<string>;
  likeCount: number;
  isLikedByCurrentUser: boolean;
};
