/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SearchResultDto } from '../models/search-result-dto';
export type SearchResponseDto = {
'results': Array<SearchResultDto>;
'sort': string;
'type': string;
'nextCursor': string | null;
};

