/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OptionalOfstring } from '../models/optional-ofstring';
export interface SelfProfilePatchRequestDto {
  avatarUrl?: OptionalOfstring;
  displayName?: OptionalOfstring;
}
