/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SelfFollowSummaryDto } from '../models/self-follow-summary-dto';
export type SelfFollowPageDto = {
  totalCount: number;
  page: number;
  pageSize: number;
  items: Array<SelfFollowSummaryDto>;
} | null;
