/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type SensitiveUserInfoDto = {
  email: string | null;
  emailConfirmed: boolean;
  phoneNumber: string | null;
  phoneNumberConfirmed: boolean;
  twoFactorEnabled: boolean;
  lockoutEnabled: boolean;
  lockoutEnd: string | null;
  roles: Array<string>;
};
