/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AggregateMetricDto } from '../models/aggregate-metric-dto';
export type SubjectAggregateDto = {
  subjectId: number;
  countReviews: number;
  avgOverall: number;
  metrics: Array<AggregateMetricDto>;
  updatedAt: string;
} | null;
