/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TwoFactorRequest {
  enable?: boolean | null;
  forgetMachine?: boolean;
  resetRecoveryCodes?: boolean;
  resetSharedKey?: boolean;
  twoFactorCode?: string | null;
}
