/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewRatingDto } from '../models/review-rating-dto';
export interface UpdateReviewDto {
  content: string | null;
  excerpt: string | null;
  ratings: Array<ReviewRatingDto> | null;
  tags: Array<string> | null;
  title: string;
}
