/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AggregateMetricDto } from '../models/aggregate-metric-dto';
export interface UpsertAggregateDto {
  avgOverall: number;
  countReviews: number;
  metrics: Array<AggregateMetricDto> | null;
}
