/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DirectoryUserDetailDto } from '../models/directory-user-detail-dto';
import { SensitiveUserInfoDto } from '../models/sensitive-user-info-dto';
export type UserDirectoryResponseDto = {
  public: DirectoryUserDetailDto;
  sensitive: SensitiveUserInfoDto | null;
};
