/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfSelfProfileDto } from '../../models/api-response-of-self-profile-dto';
import { SelfPasswordChangeRequestDto } from '../../models/self-password-change-request-dto';

export interface ApiMePasswordChangePost$Params {
      body: SelfPasswordChangeRequestDto
}

export function apiMePasswordChangePost(http: HttpClient, rootUrl: string, params: ApiMePasswordChangePost$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfSelfProfileDto>> {
  const rb = new RequestBuilder(rootUrl, apiMePasswordChangePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfSelfProfileDto>;
    })
  );
}

apiMePasswordChangePost.PATH = '/api/me/password/change';
