/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfSelfProfileDto } from '../../models/api-response-of-self-profile-dto';
import { SelfProfilePatchRequestDto } from '../../models/self-profile-patch-request-dto';

export interface ApiMePatch$Params {
  body: SelfProfilePatchRequestDto;
}

export function apiMePatch(
  http: HttpClient,
  rootUrl: string,
  params: ApiMePatch$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfSelfProfileDto>> {
  const rb = new RequestBuilder(rootUrl, apiMePatch.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfSelfProfileDto>;
    }),
  );
}

apiMePatch.PATH = '/api/me';
