/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfSelfProfileDto } from '../../models/api-response-of-self-profile-dto';

export interface ApiMeGet$Params {}

export function apiMeGet(
  http: HttpClient,
  rootUrl: string,
  params?: ApiMeGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfSelfProfileDto>> {
  const rb = new RequestBuilder(rootUrl, apiMeGet.PATH, 'get');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfSelfProfileDto>;
    }),
  );
}

apiMeGet.PATH = '/api/me';
