/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfSelfEmailTokenDispatchResponseDto } from '../../models/api-response-of-self-email-token-dispatch-response-dto';
import { SelfEmailTokenRequestDto } from '../../models/self-email-token-request-dto';

export interface ApiMeEmailTokenPost$Params {
  body: SelfEmailTokenRequestDto;
}

export function apiMeEmailTokenPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiMeEmailTokenPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfSelfEmailTokenDispatchResponseDto>> {
  const rb = new RequestBuilder(rootUrl, apiMeEmailTokenPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfSelfEmailTokenDispatchResponseDto>;
    }),
  );
}

apiMeEmailTokenPost.PATH = '/api/me/email/token';
