/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfSelfFollowerRemovalResultDto } from '../../models/api-response-of-self-follower-removal-result-dto';

export interface ApiMeFollowersUserIdDelete$Params {
  userId: string;
}

export function apiMeFollowersUserIdDelete(http: HttpClient, rootUrl: string, params: ApiMeFollowersUserIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfSelfFollowerRemovalResultDto>> {
  const rb = new RequestBuilder(rootUrl, apiMeFollowersUserIdDelete.PATH, 'delete');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfSelfFollowerRemovalResultDto>;
    })
  );
}

apiMeFollowersUserIdDelete.PATH = '/api/me/followers/{userId}';
