/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfSearchResponseDto } from '../../models/api-response-of-search-response-dto';
import { NullableOfSearchResource } from '../../models/nullable-of-search-resource';
import { NullableOfSearchSort } from '../../models/nullable-of-search-sort';

export interface ApiSearchGet$Params {
  query: string;
  type?: NullableOfSearchResource;
  sort?: NullableOfSearchSort;
  limit?: number;
  cursor?: string;
}

export function apiSearchGet(http: HttpClient, rootUrl: string, params: ApiSearchGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfSearchResponseDto>> {
  const rb = new RequestBuilder(rootUrl, apiSearchGet.PATH, 'get');
  if (params) {
    rb.query('query', params.query, {});
    rb.query('type', params.type, {});
    rb.query('sort', params.sort, {});
    rb.query('limit', params.limit, {});
    rb.query('cursor', params.cursor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfSearchResponseDto>;
    })
  );
}

apiSearchGet.PATH = '/api/search';
