/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfReviewSummaryDto } from '../../models/api-response-of-review-summary-dto';
import { CreateReviewDto } from '../../models/create-review-dto';

export interface ApiReviewsPost$Params {
  body: CreateReviewDto;
}

export function apiReviewsPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiReviewsPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfReviewSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiReviewsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfReviewSummaryDto>;
    }),
  );
}

apiReviewsPost.PATH = '/api/reviews';
