/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfReviewLikeResultDto } from '../../models/api-response-of-review-like-result-dto';

export interface ApiReviewsIdLikePost$Params {
  id: number;
}

export function apiReviewsIdLikePost(http: HttpClient, rootUrl: string, params: ApiReviewsIdLikePost$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfReviewLikeResultDto>> {
  const rb = new RequestBuilder(rootUrl, apiReviewsIdLikePost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfReviewLikeResultDto>;
    })
  );
}

apiReviewsIdLikePost.PATH = '/api/reviews/{id}/like';
