/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfReviewDetailDto } from '../../models/api-response-of-review-detail-dto';

export interface ApiReviewsIdGet$Params {
  id: number;
}

export function apiReviewsIdGet(
  http: HttpClient,
  rootUrl: string,
  params: ApiReviewsIdGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfReviewDetailDto>> {
  const rb = new RequestBuilder(rootUrl, apiReviewsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfReviewDetailDto>;
    }),
  );
}

apiReviewsIdGet.PATH = '/api/reviews/{id}';
