/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfReviewSummaryDto } from '../../models/api-response-of-review-summary-dto';
import { UpdateReviewDto } from '../../models/update-review-dto';

export interface ApiReviewsIdPut$Params {
  id: number;
  body: UpdateReviewDto;
}

export function apiReviewsIdPut(
  http: HttpClient,
  rootUrl: string,
  params: ApiReviewsIdPut$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ApiResponseOfReviewSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiReviewsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfReviewSummaryDto>;
    }),
  );
}

apiReviewsIdPut.PATH = '/api/reviews/{id}';
