/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfReviewDeleteResultDto } from '../../models/api-response-of-review-delete-result-dto';

export interface ApiReviewsIdDelete$Params {
  id: number;
}

export function apiReviewsIdDelete(http: HttpClient, rootUrl: string, params: ApiReviewsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfReviewDeleteResultDto>> {
  const rb = new RequestBuilder(rootUrl, apiReviewsIdDelete.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfReviewDeleteResultDto>;
    })
  );
}

apiReviewsIdDelete.PATH = '/api/reviews/{id}';
