/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseOfLatestReviewsPageDto } from '../../models/api-response-of-latest-reviews-page-dto';

export interface ApiReviewsLatestGet$Params {
  Page?: number;
  PageSize?: number;
  After?: string;
  AfterId?: number;
}

export function apiReviewsLatestGet(http: HttpClient, rootUrl: string, params?: ApiReviewsLatestGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseOfLatestReviewsPageDto>> {
  const rb = new RequestBuilder(rootUrl, apiReviewsLatestGet.PATH, 'get');
  if (params) {
    rb.query('Page', params.Page, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('After', params.After, {});
    rb.query('AfterId', params.AfterId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseOfLatestReviewsPageDto>;
    })
  );
}

apiReviewsLatestGet.PATH = '/api/reviews/latest';
